#!/usr/bin/env bash
# Installs HAProxy with the following configurations:
# - Enables management via the init script.
# - Distributes requests using a round-robin algorithm.

sudo apt-get install -y haproxy

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

cat <<EOT | sudo tee -a /etc/haproxy/haproxy.cfg
frontend tahrijouteyamer.tech
    timeout client  30000
    bind 0:80
    default_backend tahrijouteyamer.tech_backend

backend tahrijouteyamer.tech_backend
    timeout connect  3000
    timeout server  30000
    balance roundrobin
    server 367946-web-01 54.198.51.49 check
    server 367946-web-02 18.207.142.50 check
EOT

sudo service haproxy restart
