#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

# Install HAproxy on a server
apt-get -y update
apt-get -y install haproxy=1.6.\*

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
echo '
frontend tahrijouteyamer.tech
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 367946-web-01 54.198.51.49
        server 367946-web-02 18.207.142.50
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
service haproxy restart
